"""empty message

Revision ID: 834e7cbcebb1
Revises: c22a710b8240
Create Date: 2025-09-02 15:49:23.046448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834e7cbcebb1'
down_revision = 'c22a710b8240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
